services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ~/.aws:/root/.aws:ro  # Mount AWS credentials as read-only
      - output-data:/app/output
    environment:
      - FLASK_APP=aws_finops_dashboard.api
      - HOST=0.0.0.0
      - PORT=5001
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001  # API URL for client-side
      - API_URL=http://backend:5001  # API URL for server-side
    restart: unless-stopped

volumes:
  output-data:
    # Persistent volume for reports and output files 